easy_admin:
   site_name: 'Symfony <em style="font-size: 80%;">Assignment.</em>'
   list:
        max_results: 5
   entities:
        # List the entity class name you want to manage
        Platform:
            class: App\Entity\Platform
            label: 'Platforms'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
            form:
                fields:
                    - { property: 'name', type: 'text', type_options: { required: true } }
        Provider:
            class: App\Entity\Provider
            label: 'Providers'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
                    - description
            form:
                fields:
                    - { property: 'name', type: 'text' , type_options: { required: true } }
                    - { property: 'description' , type: 'textarea' , type_options: { required: true }}
                    - Platform
        Bundle:
            class: App\Entity\Bundle
            label: 'Bundles'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
                    - description
                    - price
                    - { property: 'image', type: 'image', base_path: '/uploads/' }
            form:
                fields:
                    - { property: 'name', type: 'text' , type_options: { required: true } }
                    - { property: 'description', type: 'textarea' , type_options: { required: true } }
                    - { property: 'price', type: 'text' , type_options: { required: true } }
                    - { property: 'image' , type: 'file_upload' , type_options: { upload_dir: 'public/uploads/',required: true }}
                    - Provider
                    - Platform