easy_admin:
   site_name: 'Symfony <em style="font-size: 80%;">Assignment.</em>'
   list:
        max_results: 5
   entities:
        # List the entity class name you want to manage
        Platform:
            class: App\Entity\Platform
            label: 'Platforms'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
        Provider:
            class: App\Entity\Provider
            label: 'Providers'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
                    - description
        Bundle:
            class: App\Entity\Bundle
            label: 'Bundles'
            list:
                title: '%%entity_label%% Listing'
                fields:
                    - id
                    - name
                    - description
                    - price
                    - { property: 'image', type: 'image' }